name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # - name: Setup PNPM
      #   uses: pnpm/action-setup@v2.1.0
      #   with:
      #     version: 6.30.1
      #     run_install: true

      # - name: Build assets
      #   run: pnpm build-prod-assets

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "podvapor"
          entrypoint: "./backend/app.ts"